FROM node:20-alpine AS build

ARG VITE_API_URL=""
ENV VITE_API_URL=$VITE_API_URL

WORKDIR /app

COPY app/Front_End/package.json app/Front_End/package-lock.json* ./

RUN npm install react@18.3.1 react-dom@18.3.1 && npm install

COPY app/Front_End/ .

RUN npm run build

FROM nginx:alpine

COPY deploy/nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
